language: php

php:
  - 5.6
  - 7.0

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

install: travis_retry composer require "laravel/framework:5.1.*"

script: php vendor/bin/phpunit --configuration phpunit.xml.dist